services:
  precifica-3d:
    build:
      context: .
      dockerfile: Dockerfile
    image: precifica-3d:latest
    container_name: precifica-3d
    restart: unless-stopped
    ports:
      - "5172:5172"
    environment:
      - PORT=5172
      - HOST=0.0.0.0
      - DATA_DIR=/app/data
      - NODE_ENV=production
    volumes:
      - /DATA/AppData/precifica-3d:/app/data
